

import datetime
import numpy as np
import netCDF4 as nc
import sys
import re
import InterpUtilities as iutil
flin0=sys.argv[1]
flin1=sys.argv[2]
flout=sys.argv[3]

varname0=sys.argv[4]
varname=varname0.split(":")
nvar=len(varname)

data0 = nc.Dataset(flin0,"r")
t=np.asarray(data0["time"][:])
var=np.asarray(data0["ErrorVariance"][:,:])
x=np.asarray(data0["longitude"][:])
y=np.asarray(data0["latitude"][:])
e=np.asarray(data0["tri"][:,:])

nt=len(t)
nn=len(x)
ne=e.shape[0]

nvar=len(varname)
field=np.zeros(nvar,nt,nn)

nan=float("nan")
for jv in range(nvar):
    tmp=np.asarray(data0[varname[jv]][:,:])
    fill_value0=data0[varname[jv]]._FillValue
    tmp[np.where(tmp==fill_value0)]=nan
    field[jv,:,:]=tmp

data1 = nc.Dataset(flin1,"r")
t1=np.asarray(data1["time"][:])
var1=np.asarray(data1["ErrorVariance"][:,:])
nt1,nn1=var1.shape
field1=np.zeros(nvar,nt1,nn1)
for jv in range(nvar):
    tmp=np.asarray(data1[varname[jv]][:,:])
    fill_value1=data1[varname[jv]]._FillValue
    tmp[np.where(tmp==fill_value1)]=nan
    field[jv,:,:]=tmp


um1=field1[0,0,:]
ng1=np.where(um1**2>=0) #find points that are valid floats for field1
for k in range(nt):
    j=np.where(t[k]==t1) # find common merge point in data
    j=j[0].tolist()
    if len(j)==1:
        print("j="+str(j)+" : k="+str(k))
        for jv in range(nvar):
             field[jv,k,ng1] =  ( field[jv,k,ng1] 
                                    +  ( var[k,ng1] / ( var[k,ng1] + var1[j,ng1] ) ) 
                                    * (field1[jv,j,ng1]-field[jv,k,ng1])
                                )
        #update error variance to posterior
        var[k,ng1]=var[k,ng1] * ( var1[j,ng1] / ( var[k,ng1]+var1[j,ng1] ) )

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:
    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=x[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=y[:]
        
    var=data0["time"]
    time_var=ncout.createVariable(varname[jv], 'f4', ('time','node'))
    iutil.CopyAttributes(var, time_var)
    time_var[:]=t[:]
"""
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
"""
    tri_var=ncout.createVariable('tri', 'i4', ('element','noel'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:,:]=e

    #Copy attributes from old file to new
    for jv in range(nvar):
        var=data0[varname[jv]]
        f_var=ncout.createVariable(varname[jv], 'f4', ('time','node'))
        util.CopyAttributes(var, f_var)
        f_var[:,:]=field[jv,:,:]
#        att_names = var.ncattrs()
#        for jatt in range(len(att_names)):
#            att_name=att_names[jatt]
#            if (not (att_name=="_FillValue")):
#                att_value = var.getncattr(att_name)
#                print(att_name+" : ")
#                print(att_value)
#                f_var.setncattr(att_name, att_value)

    ErrVar0=data0["ErrorVariance"]
    ErrVar_var=ncout.createVariable("ErrorVariance", 'f4', ('time','node'))
    iutil.CopyAttributes(ErrVar0, ErrVar_var)
    vari_var[:,:]=var[:,:]

"""    
    att_names = ErrVar0.ncattrs()
    for jatt in range(len(att_names)):
        att_name=att_names[jatt]
        if (not (att_name=="_FillValue")):
            att_value = var.getncattr(att_name)
            ErrVar_var.setncattr(att_name, att_value)
        f_var[:,:]=field[jv,:,:]
    vari_var=ncout.createVariable('ErrorVariance', 'f4', ('time','node'))
    vari_var.long_name     = 'error variance of wind estimate'
    vari_var.units         = 'm m / s / s'
    vari_var.standard_name = 'error variance of wind estimate'
    vari_var.level = '10 m above ground'
    vari_var[:,:]=var[:,:]
"""        

    ncout.close
