# Consolidate u,v surface currents from 
import numpy as np
import os
import netCDF4 as nc
import sys

# Get the path relative to this file and add to sys.path
#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'utils')))
#import helper
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import InterpUtilities as  iutil

dirin=sys.argv[1]
flout=sys.argv[2]

ncfiles = os.listdir(dirin)
print(ncfiles)
nt=len(ncfiles)
k=0    
flin=dirin+"/"+ncfiles[k]
data=nc.Dataset(flin,"r")
X=data["Longitude"][:,:]
Y=data["Latitude"][:,:]
fill_value0=data["u_velocity"]._FillValue
nx=X.shape[0]
ny=X.shape[1]
U=np.zeros((nt,1,nx,ny))
V=np.zeros((nt,1,nx,ny))
MT=np.zeros(nt)
time=np.zeros(nt)
print(U.shape)
for k in range(nt):
    flin=dirin+"/"+ncfiles[k]
    data=nc.Dataset(flin,"r")
    U0=data["u_velocity"][:]
    V0=data["v_velocity"][:]    
    T0=data["MT"][:]    
    print(k)
    U[k,0,:,:]=U0[0,0,:,:]
    V[k,0,:,:]=V0[0,0,:,:]
    MT[k]=T0
    tmp=iutil.ConvertTimeToUnixTime(flin,"MT")
    time[k]=tmp[0]

tindx = np.argsort(time)
time=time[tindx]
MT=MT[tindx]
U=U[tindx,:,:,:]
V=V[tindx,:,:,:]

Layers=data["Layer"][:]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('Layer' , 1)  
    ncout.createDimension('X' , nx)
    ncout.createDimension('Y' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('longitude', 'f4', ('X','Y'))
    var=data["Longitude"]
    iutil.CopyAttributes(var, lon_var)
    lon_var[:,:]=X[:,:]

    lat_var=ncout.createVariable('latitude', 'f4', ('X','Y'))
    var=data["Latitude"]
    iutil.CopyAttributes(var, lat_var)
    lat_var[:,:]=Y[:,:]
    
    # Keep redundent time variables (time and MT) for conviniences
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var[:] = time[:]
    
    MT_var=ncout.createVariable("MT", 'f8', ('time',))
    var=data["MT"]
    iutil.CopyAttributes(var, MT_var)
    MT_var[:] = MT[:]

    u_var               = ncout.createVariable('u-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    var=data["u_velocity"]
    iutil.CopyAttributes(var, u_var)
    u_var[:,:,:,:]      = U

    v_var               = ncout.createVariable('v-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    var=data["v_velocity"]
    iutil.CopyAttributes(var, v_var)
    v_var[:,:,:,:]      = V
    
    l_var           = ncout.createVariable('Layer', 'i4', ('Layer',))
    var=data["Layer"]
    iutil.CopyAttributes(var, l_var)
    l_var[:] = Layers[0]
