# Consolidate u,v surface currents from 
import numpy as np
import os
import netCDF4 as nc
import sys
import InterpNWPSUtility as  mshutil

dirin=sys.argv[1]
flout=sys.argv[2]

ncfiles = os.listdir(dirin)
print(ncfiles)
nt=len(ncfiles)
k=0    
flin=dirin+"/"+ncfiles[k]
data=nc.Dataset(flin,"r")
X=data["Longitude"][:,:]
Y=data["Latitude"][:,:]
fill_value0=data["u_velocity"]._FillValue
nx=X.shape[0]
ny=X.shape[1]
U=np.zeros((nt,1,nx,ny))
V=np.zeros((nt,1,nx,ny))
MT=np.zeros(nt)
time=np.zeros(nt)
print(U.shape)
for k in range(nt):
    flin=dirin+"/"+ncfiles[k]
    data=nc.Dataset(flin,"r")
    U0=data["u_velocity"][:]
    V0=data["v_velocity"][:]    
    T0=data["MT"][:]    
    print(k)
    U[k,0,:,:]=U0[0,0,:,:]
    V[k,0,:,:]=V0[0,0,:,:]
    MT[k]=T0
    tmp=mshutil.ConvertTimeToUnixTime(flin,"MT")
    time[k]=tmp[0]

Layers=data["Layer"][:]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('Layer' , 1)  
    ncout.createDimension('X' , nx)
    ncout.createDimension('Y' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('Longitude', 'f4', ('X','Y'))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:,:]=X[:,:]

    lat_var=ncout.createVariable('Latitude', 'f4', ('X','Y'))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:,:]=Y[:,:]
    
    # Keep redundent time variables (time and MT) for conviniences
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var[:]=time[:]

    varin           = data["MT"]
    units           = varin.units 
    long_name       = varin.long_name
    calendar        =varin.calendar

    MT_var=ncout.createVariable("MT", 'f8', ('time',))
    MT_var.long_name     = long_name
    MT_var.standard_name = long_name
    MT_var.units         = units
    MT_var.axis          = 'T'
    MT_var.calendar      = calendar
    MT_var[:]            = MT[:]

    u_var               = ncout.createVariable('u-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    u_var.standard_name = 'eastward_sea_surface_water_velocity'
    u_var.units         = 'm/s'
    u_var.long_name     = ' u-veloc. [93.1H]'
    u_var.level         = 'layer 1 from:'+flin
    u_var[:,:,:,:]      = U

    v_var               = ncout.createVariable('v-vel', 'f4', ('time','Layer','X','Y'),fill_value    = fill_value0)
    v_var.standard_name = 'northward_sea_surface_water_velocity'
    v_var.units         = 'm/s'
    v_var.long_name     = ' v-veloc. [93.1H]''northward_wind'
    v_var.level         = 'layer 1 from:'+flin
    v_var[:,:,:,:]      = V
    
    l_var           = ncout.createVariable('Layer', 'i4', ('Layer',))
    l_var.units     = 'layer'
    l_var.positive  = 'down'
    l_var.axis      = 'Z'
    l_var[:]        = Layers[0]
