# aws s3 cp --no-sign-request s3://noaa-nws-rtofs-pds/rtofs.20260115/ ./rtofs_jan2026_ice/ --recursive --exclude "*" --include "*ice*"
#Consolidate ice_coverage from RTOFS forecast files 
import numpy as np
import os
import netCDF4 as nc
import sys

# Get the path relative to this file and add to sys.path
#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'utils')))
#import helper
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import InterpUtilities as  iutil

dirin=sys.argv[1]
flout=sys.argv[2]

ncfiles = os.listdir(dirin)
print(ncfiles)
nt=len(ncfiles)
k=0
flin=dirin+"/"+ncfiles[k]
data=nc.Dataset(flin,"r")
X=data["Longitude"][:,:]
Y=data["Latitude"][:,:]
fill_value0=data["ice_coverage"]._FillValue
nx=X.shape[0]
ny=X.shape[1]
F=np.zeros((nt,nx,ny),dtype=np.float32)
MT=np.zeros(nt)
time=np.zeros(nt)
print("nx = "+str(nx))
print("ny = "+str(ny))
print(F.shape)
for k in range(nt):
    flin=dirin+"/"+ncfiles[k]

    flinT=flin.replace("Ice","")
    flinT=flinT.replace("ice","prog")
    
    print("ICE: org flin="+flin+" Time flin="+flinT)

    dataT=nc.Dataset(flinT,"r")

    data=nc.Dataset(flin,"r")
    F0=data["ice_coverage"][:]
#    T0=data["MT"][:]    
    T0=dataT["MT"][:]    

    print(F0.shape)
    print(F.shape)
    print(str(k)+" of "+ str(nt))
    F[k,:,:]=F0[0,:,:]
    MT[k]=T0
#    tmp=iutil.ConvertTimeToUnixTime(flin,"MT")

    tmp=iutil.ConvertTimeToUnixTime(flinT,"MT")

    time[k]=tmp[0]

#-rw-r--r-- 1 keston.smith couple 64M Jul 29 17:59 tmp.rtofsIce.20260728/rtofs_glo_2ds_f007_ice.nc
#-rw-r--r-- 1 keston.smith couple 64M Jul 29 17:59 tmp.rtofsIce.20260728/rtofs_glo_2ds_n007_ice.nc
#keston.smith@dlogin06:/lfs/h2/emc/couple/noscrub/keston.smith/RWPSInterpolationUtilities> l tmp.rtofs.20260728/*007*nc
#-rw-r--r-- 1 keston.smith couple 149M Jul 29 17:49 tmp.rtofs.20260728/rtofs_glo_2ds_f007_prog.nc
#-rw-r--r-- 1 keston.smith couple 149M Jul 29 17:50 tmp.rtofs.20260728/rtofs_glo_2ds_n007_prog.nc




tindx = np.argsort(time)
time=time[tindx]
MT=MT[tindx]
F=F[tindx,:,:]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('X' , nx)
    ncout.createDimension('Y' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('longitude', 'f4', ('X','Y'))
    var=data["Longitude"]
    iutil.CopyAttributes(var, lon_var)
    lon_var[:,:]=X[:,:]

    lat_var=ncout.createVariable('latitude', 'f4', ('X','Y'))
    var=data["Latitude"]
    iutil.CopyAttributes(var, lat_var)
    lat_var[:,:]=Y[:,:]
    
    # Keep redundent time variables (time and MT) for conviniences
    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var[:] = time[:]
    
    MT_var=ncout.createVariable("MT", 'f8', ('time',))
    var=data["MT"]
    iutil.CopyAttributes(var, MT_var)
    MT_var[:] = MT[:]

#    f_var               = ncout.createVariable('ice_coverage', 'f4', ('time','X','Y'),fill_value    = fill_value0)
    f_var               = ncout.createVariable('ICEC_surface', 'f4', ('time','X','Y'),fill_value    = fill_value0)
    var=data["ice_coverage"]
    iutil.CopyAttributes(var, f_var)
    f_var[:,:,:]      = F[:,:,:]
